import React, { useEffect, useState } from 'react';
import { Link } from 'react-router-dom';
import { api } from '../services/api.js';
import { Card } from '../components/Card.js';
import { Badge } from '../components/Badge.js';
import type { Investigation } from '../types/index.js';

/* ── Static demo postmortems (clearly labeled) ── */
interface Postmortem {
  id: string;
  title: string;
  severity: string;
  detectedAt: string;
  resolvedAt?: string;
  durationMin: number;
  rootCause: string;
  services: string[];
  timeline: { time: string; event: string; type: 'info' | 'success' | 'error' | 'warn' }[];
  wentWell: string[];
  actions: string[];
  source: 'live' | 'demo';
  investigationId?: string;
}

const DEMO_POSTMORTEMS: Postmortem[] = [
  {
    id: 'PM-002',
    title: 'Dashboard empty — all API calls returning 404',
    severity: 'P0',
    detectedAt: '2026-02-24T12:05:00Z',
    resolvedAt: '2026-02-24T12:25:00Z',
    durationMin: 20,
    rootCause: 'Frontend API client read import.meta.env.VITE_API_BASE instead of VITE_API_URL, causing undefined base URL in all requests.',
    services: ['frontend', 'insightboard-api'],
    timeline: [
      { time: '12:05', event: 'User reports dashboard empty since last deploy', type: 'error' },
      { time: '12:08', event: 'Investigation started', type: 'info' },
      { time: '12:12', event: 'Evidence Agent: /undefined/ in request paths', type: 'success' },
      { time: '12:15', event: 'Code Agent: VITE_API_BASE vs VITE_API_URL mismatch found', type: 'success' },
      { time: '12:18', event: 'Root cause confirmed', type: 'success' },
      { time: '12:20', event: 'Fix approved and applied', type: 'info' },
      { time: '12:25', event: 'Dashboard loading normally — resolved', type: 'success' },
    ],
    wentWell: ['Root cause identified in under 10 minutes', 'Minimal patch — 1 token change', 'No data loss'],
    actions: ['Add env variable naming convention to team docs', 'Add startup validation for required env vars'],
    source: 'demo',
  },
  {
    id: 'PM-001',
    title: 'Orders API returning 500 — SQL column not found',
    severity: 'P1',
    detectedAt: '2026-02-24T14:21:00Z',
    resolvedAt: '2026-02-24T14:33:00Z',
    durationMin: 12,
    rootCause: 'SQL query in orders route referenced o.customer_name which does not exist. Correct column is o.customer.',
    services: ['orders-api', 'insightboard-backend'],
    timeline: [
      { time: '14:21', event: 'First error detected in server logs', type: 'error' },
      { time: '14:24', event: 'Database Agent identified SQL column mismatch', type: 'success' },
      { time: '14:27', event: 'Root cause confirmed', type: 'success' },
      { time: '14:30', event: 'Human approved fix plan', type: 'info' },
      { time: '14:31', event: 'Fix applied — 1 file, 1 line', type: 'success' },
      { time: '14:33', event: 'All tests passing — incident resolved', type: 'success' },
    ],
    wentWell: ['Agents identified root cause in under 4 minutes', 'Minimal patch', 'All regression tests passed'],
    actions: ['Add SQL column name tests at startup', 'Review ORM migration process'],
    source: 'demo',
  },
];

function downloadMarkdown(pm: Postmortem) {
  const lines = [
    `# Postmortem: ${pm.id} — ${pm.title}`,
    '',
    `**Severity:** ${pm.severity}  `,
    `**Detected:** ${new Date(pm.detectedAt).toLocaleString()}  `,
    pm.resolvedAt ? `**Resolved:** ${new Date(pm.resolvedAt).toLocaleString()}  ` : '',
    `**Duration:** ${pm.durationMin} minutes  `,
    `**Services:** ${pm.services.join(', ')}`,
    '',
    '---',
    '',
    '## Root Cause',
    '',
    pm.rootCause,
    '',
    '## Timeline',
    '',
    ...pm.timeline.map((e) => `- **${e.time}** — ${e.event}`),
    '',
    '## What Went Well',
    '',
    ...pm.wentWell.map((w) => `- ${w}`),
    '',
    '## Corrective Actions',
    '',
    ...pm.actions.map((a) => `- ${a}`),
    '',
    '---',
    '',
    '*Generated by FixFlow AI*',
  ].join('\n');

  const blob = new Blob([lines], { type: 'text/markdown' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = `postmortem-${pm.id.toLowerCase()}.md`;
  a.click();
  URL.revokeObjectURL(url);
}

export function PostmortemsPage() {
  const [selected, setSelected] = useState<Postmortem | null>(DEMO_POSTMORTEMS[0]);
  const [tab, setTab] = useState<'list' | 'detail'>('list');
  const [postmortems, setPostmortems] = useState<Postmortem[]>(DEMO_POSTMORTEMS);

  /* Pull completed investigations and build live postmortems */
  useEffect(() => {
    api.listInvestigations()
      .then(({ investigations }) => {
        const completed = investigations.filter((i: any) => i.status === 'completed');
        if (completed.length === 0) return;
        Promise.all(
          completed.slice(0, 3).map((inv: any) =>
            api.getInvestigation(inv.id)
              .then(({ investigation: i }) => i)
              .catch(() => null)
          )
        ).then((results) => {
          const live: Postmortem[] = (results.filter(Boolean) as Investigation[])
            .map((inv) => ({
              id: `PM-${inv.id.slice(0, 6).toUpperCase()}`,
              title: inv.bug.title,
              severity: inv.bug.severity === 'critical' ? 'P0' : inv.bug.severity === 'high' ? 'P1' : 'P2',
              detectedAt: inv.createdAt,
              resolvedAt: inv.updatedAt,
              durationMin: Math.round((new Date(inv.updatedAt).getTime() - new Date(inv.createdAt).getTime()) / 60000),
              rootCause: inv.rootCause?.statement ?? inv.bug.description.slice(0, 200),
              services: inv.projectMap?.components.map((c) => c.name).slice(0, 3) ?? [inv.projectName],
              timeline: inv.activity.slice(0, 8).reverse().map((e, i) => ({
                time: new Date(e.at).toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' }),
                event: e.message,
                type: (e.level === 'error' ? 'error' : e.level === 'success' ? 'success' : e.level === 'warn' ? 'warn' : 'info') as Postmortem['timeline'][number]['type'],
              })),
              wentWell: [
                `${inv.agents.filter((a) => a.status === 'completed').length} agents completed successfully`,
                inv.verification?.status === 'passed' ? 'All verification checks passed' : 'Fix applied',
                inv.regression?.status === 'clean' ? 'No regressions detected' : 'Regression check ran',
              ].filter(Boolean),
              actions: inv.report?.recommendedFollowUp
                ? inv.report.recommendedFollowUp.split('\n').filter(Boolean).slice(0, 3)
                : ['Review affected components', 'Add regression tests'],
              source: 'live' as const,
              investigationId: inv.id,
            }));

          if (live.length > 0) {
            setPostmortems([...live, ...DEMO_POSTMORTEMS]);
            setSelected(live[0]);
          }
        });
      })
      .catch(() => {});
  }, []);

  const livePMs = postmortems.filter((p) => p.source === 'live');
  const hasLive = livePMs.length > 0;

  const SEV_COLOR: Record<string, string> = { P0: 'var(--danger)', P1: 'var(--danger)', P2: 'var(--warn)', P3: 'var(--info)' };
  const TYPE_COLOR = { info: 'var(--info)', success: 'var(--success)', error: 'var(--danger)', warn: 'var(--warn)' };

  return (
    <div className="page-content stack" style={{ gap: 22 }}>
      {/* Header */}
      <div className="spread">
        <div>
          <h1 className="page-title">Postmortems</h1>
          <p className="muted" style={{ marginTop: 8, fontSize: 13 }}>
            Incident analysis, timelines, root causes, and corrective actions.
          </p>
        </div>
        {hasLive
          ? <Badge variant="success" dot>LIVE + DEMO</Badge>
          : <span className="demo-notice">DEMO DATA</span>}
      </div>

      {/* Metrics */}
      <div className="metric-grid">
        <div className="metric">
          <p className="metric-value">{postmortems.length}</p>
          <p className="metric-label">Total postmortems</p>
        </div>
        <div className="metric">
          <p className="metric-value" style={{ color: 'var(--success)' }}>{livePMs.length}</p>
          <p className="metric-label">From live investigations</p>
        </div>
        <div className="metric">
          <p className="metric-value" style={{ color: 'var(--warn)' }}>
            {postmortems.length > 0
              ? Math.round(postmortems.reduce((a, p) => a + p.durationMin, 0) / postmortems.length)
              : 0}m
          </p>
          <p className="metric-label">Avg resolution time</p>
        </div>
        <div className="metric">
          <p className="metric-value" style={{ color: 'var(--accent)' }}>
            {postmortems.filter(p => p.resolvedAt).length}/{postmortems.length}
          </p>
          <p className="metric-label">Resolved</p>
        </div>
      </div>

      <div className="tabs" role="tablist">
        <button role="tab" aria-selected={tab === 'list'} className="tab" onClick={() => setTab('list')}>
          All Postmortems
        </button>
        <button role="tab" aria-selected={tab === 'detail'} className="tab" onClick={() => setTab('detail')} disabled={!selected}>
          {selected?.id ?? 'Detail'}
        </button>
      </div>

      {tab === 'list' && (
        <div className="stack" style={{ gap: 12 }}>
          {postmortems.map((pm) => (
            <button
              key={pm.id}
              className="panel"
              style={{
                padding: '16px 20px', textAlign: 'left', cursor: 'pointer', width: '100%',
                borderLeft: `3px solid ${SEV_COLOR[pm.severity] ?? 'var(--line)'}`,
                background: selected?.id === pm.id ? 'rgba(124,92,252,.04)' : undefined,
              }}
              onClick={() => { setSelected(pm); setTab('detail'); }}
            >
              <div className="spread">
                <div className="row" style={{ gap: 10 }}>
                  <span className="chip mono" style={{ fontSize: 10, color: SEV_COLOR[pm.severity] }}>
                    {pm.severity}
                  </span>
                  <span style={{ fontSize: 14, fontWeight: 700, color: 'var(--ink)' }}>{pm.title}</span>
                </div>
                <div className="row" style={{ gap: 6 }}>
                  {pm.source === 'live'
                    ? <Badge variant="success" dot>LIVE</Badge>
                    : <span className="demo-notice">DEMO</span>}
                  <Badge variant={pm.resolvedAt ? 'success' : 'danger'} dot>
                    {pm.resolvedAt ? 'resolved' : 'open'}
                  </Badge>
                </div>
              </div>
              <div className="row" style={{ gap: 14, marginTop: 10 }}>
                <span style={{ fontSize: 12, color: 'var(--muted)' }}>Duration: {pm.durationMin}m</span>
                <span style={{ fontSize: 12, color: 'var(--muted)' }}>Services: {pm.services.slice(0, 2).join(', ')}</span>
                <span style={{ fontSize: 12, color: 'var(--muted)' }}>
                  {new Date(pm.detectedAt).toLocaleDateString()}
                </span>
              </div>
              <p style={{ margin: '10px 0 0', fontSize: 12, color: 'var(--subtle)', lineHeight: 1.6 }} className="truncate-2">
                Root cause: {pm.rootCause}
              </p>
            </button>
          ))}
        </div>
      )}

      {tab === 'detail' && selected && (
        <div className="stack" style={{ gap: 16 }}>
          <Card title={`${selected.id} — ${selected.title}`} action={
            <div className="row" style={{ gap: 6 }}>
              {selected.source === 'live'
                ? <Badge variant="success" dot>LIVE</Badge>
                : <span className="demo-notice">DEMO</span>}
              <Badge variant={selected.resolvedAt ? 'success' : 'danger'} dot>
                {selected.resolvedAt ? 'resolved' : 'open'}
              </Badge>
            </div>
          }>
            <div className="stack" style={{ gap: 14 }}>
              <dl className="kv" style={{ rowGap: 8 }}>
                <dt>Severity</dt>
                <dd style={{ color: SEV_COLOR[selected.severity], fontWeight: 700 }}>{selected.severity}</dd>
                <dt>Duration</dt>
                <dd>{selected.durationMin} minutes</dd>
                <dt>Services</dt>
                <dd>{selected.services.join(', ')}</dd>
                <dt>Detected</dt>
                <dd className="mono" style={{ fontSize: 12 }}>{new Date(selected.detectedAt).toLocaleString()}</dd>
                {selected.resolvedAt && (
                  <><dt>Resolved</dt><dd className="mono" style={{ fontSize: 12 }}>{new Date(selected.resolvedAt).toLocaleString()}</dd></>
                )}
                {selected.investigationId && (
                  <><dt>Investigation</dt>
                  <dd>
                    <Link to={`/investigations/${selected.investigationId}`} style={{ color: 'var(--accent)', fontSize: 12 }}>
                      {selected.investigationId.slice(0, 8)} →
                    </Link>
                  </dd></>
                )}
              </dl>

              <Section label="Root Cause">{selected.rootCause}</Section>

              <div>
                <p style={{ margin: '0 0 10px', fontSize: 11, fontWeight: 700, color: 'var(--subtle)', textTransform: 'uppercase', letterSpacing: '.08em' }}>
                  Incident Timeline
                </p>
                <div className="timeline">
                  {selected.timeline.map((ev, i) => (
                    <div key={i} className="timeline-item">
                      <div className="timeline-dot" style={{ background: TYPE_COLOR[ev.type] }} />
                      <span className="timeline-time mono">{ev.time}</span>
                      <span className="timeline-event">{ev.event}</span>
                    </div>
                  ))}
                </div>
              </div>

              <div className="card-grid-2" style={{ gap: 12 }}>
                <Section label="What Went Well">
                  {selected.wentWell.map((w, i) => (
                    <div key={i} style={{ marginBottom: 4 }}>• {w}</div>
                  ))}
                </Section>
                <Section label="Corrective Actions">
                  {selected.actions.map((a, i) => (
                    <div key={i} style={{ marginBottom: 4 }}>• {a}</div>
                  ))}
                </Section>
              </div>

              <div className="row" style={{ gap: 8 }}>
                <button
                  className="btn btn-primary btn-sm"
                  onClick={() => downloadMarkdown(selected)}
                >
                  ↓ Export Markdown
                </button>
                <button className="btn btn-sm" onClick={() => setTab('list')}>
                  ← Back to list
                </button>
                {selected.investigationId && (
                  <Link to={`/investigations/${selected.investigationId}`} className="btn btn-sm">
                    View investigation →
                  </Link>
                )}
              </div>
            </div>
          </Card>
        </div>
      )}
    </div>
  );
}

function Section({ label, children }: { label: string; children: React.ReactNode }) {
  return (
    <div style={{ padding: '10px 14px', background: 'var(--panel-sunken)', borderRadius: 10, border: '1px solid var(--line)' }}>
      <p style={{ margin: '0 0 6px', fontSize: 11, fontWeight: 700, color: 'var(--subtle)', textTransform: 'uppercase', letterSpacing: '.08em' }}>{label}</p>
      <div style={{ margin: 0, fontSize: 12.5, color: 'var(--muted)', lineHeight: 1.65 }}>{children}</div>
    </div>
  );
}
